### ISSUE TITLE
Firefox 18 OSX and Win7 loaded-event triggered before image is loaded.

### ISSUE THREAD

**Issue by cjohansson52** [desandro/imagesloaded#50] opened 2013-01-18 00:12 UTC
I'm not sure if I'm doing something wrong or if something is going on in Firefox on this page: http://fl.chrisjohansson.com/gallery/lega-figure/ (and it's siblings).

The summary is: I hide an image, show a loader, switch out the img src, run imagesLoaded and show the image again. This works splendidly in all tested browsers. 

However, it seems firefox is triggering events before the image is loaded. So while it's doing all that it should it's not actually waiting for the image to load. It reminds me of some issue I think I read somewhere about it thinking an image is cached when it isn't. I'm just not good enough at debugging to be able to pinpoint that.

It works in all other tested browsers.

Thanks!

**Comment by desandro** [comment] 2015-10-29 11:27
imagesLoaded v3.2.0 has a [fix for the Firefox hang up](https://github.com/desandro/imagesloaded/blob/v3.2.0/imagesloaded.js#L287-L289). [Try it out] and report back if you feel this issue has been resolved.

**Comment by danxshap** [comment] 2015-11-03 00:14
@desandro issue does not appear to be resolved: http://plnkr.co/edit/kaaCwMc2oN5gBEn4UNRb?p=preview

The exact same behavior as I described above / last year still happens with the latest library.

**Comment by desandro** [comment] 2015-11-03 03:06
@danxshap I'm not able to reproduce the bug with this test case

**Comment by danxshap** [comment] 2015-11-03 05:20
@desandro here's a screencast with the latest libraries demonstrating the issue: http://d.pr/v/11Yos

Anyone else seeing this too?

**Comment by desandro** [comment] 2015-11-03 12:31
@danxshap Ah, thanks for reminding me of the original issue — imagesLoaded triggers before the image has completely rendered on screen. Okay, I'll keep this issue open.

**Comment by desandro** [comment] 2018-01-02 16:27
This issue has been quiet for a while. I'm going to to close it. Please open a new separate issue if you run into trouble with Firefox or Windows.

**Closed by desandro** 2018-01-02 16:27 UTC
