### ISSUE TITLE
image in inline svg?

### ISSUE THREAD

**Issue by illycz** [desandro/imagesloaded#271] opened 2018-01-13 19:02 UTC
Is it possible check this?

**Comment by desandro** [comment] 2018-01-14 14:07
Currently, no, imagesLoaded does not officially support `<image>` elements within inline `<svg>`.

**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment] 2022-02-09 03:39
Closing as a duplicate of #277 . Add a 👍 there!

**Closed by desandro** 2022-02-09 03:39 UTC
Labels: feature request
