### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by voltmn** [desandro/imagesloaded#212] opened 2015-11-12 17:36 UTC
And what about SVG images?

**Comment by desandro** [comment] 2022-02-09 03:38
**Add a 👍  reaction** to this issue if you would like to see this imagesLoaded add support for `<svg>`, including images within SVG. Do not add +1 comments — [They will be deleted](https://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment] 2022-02-09 03:40
Closing as a duplicate of #277. Add a 👍 there!

**Closed by desandro** 2022-02-09 03:40 UTC
Labels: feature request
